data:
  operations:
    - name: install-cluster
      title:
        zh: 安装集群
        en: Install Cluster
      steps:
        - name: 01-init-os
          title:
            zh: 初始化操作系统
            en: Init Operating System
        - name: 02-install-cri
          title:
            zh: 安装容器运行时
            en: Install Container Runtime Engine
        - name: 03-install-etcd
          title:
            zh: 安装 ETCD
            en: Install ETCD
        - name: 04-install-k8s
          title:
            zh: 安装 K8S 控制节点
            en: Install Control Plane
          mark_pangeecluster_node_action_done:
            ansible_group: 
              - all.children.target.children.k8s_cluster.children.kube_control_plane
            action: add_node
        - name: 05-join-k8s
          title:
            zh: 安装 K8S 工作节点
            en: Install Node
          mark_pangeecluster_node_action_done:
            ansible_group: 
              - all.children.target.children.k8s_cluster.children.kube_node
            action: add_node
          mark_pangeecluster_status:
            name: all.vars.pangeecluster_status
            value: installed
    - name: add-node
      title:
        zh: 添加节点
        en: Add Node
      pangeecluster_node_action: add_node
      enabled_on:
        - variable: all.vars.pangeecluster_status
          operator: equal
          value: installed
      steps:
        - name: 01-init-os
          title:
            zh: 初始化操作系统
            en: Init Operating System
        - name: 02-install-cri
          title:
            zh: 安装容器运行时
            en: Install Container Runtime Engine
        - name: 03-join-k8s
          title:
            zh: 安装 K8S 工作节点
            en: Install Node
          mark_pangeecluster_node_action_done:
            ansible_group: 
              - all.children.target.children.k8s_cluster.children.kube_control_plane
              - all.children.target.children.k8s_cluster.children.kube_node
            action: add_node
    - name: delete-node
      pangeecluster_node_action: delete_node
      title:
        zh: 删除节点
        en: Delete Node
      enabled_on:
        - variable: all.vars.pangeecluster_status
          operator: equal
          value: installed
      steps:
        - name: 01-remove-from-cluster
          title:
            zh: 从集群删除节点
            en: Remote Node from Cluster
        - name: 02-reset-node
          title:
            zh: 重置节点
            en: Reset Node
          mark_pangeecluster_node_action_done:
            ansible_group: 
              - all.children.target.children.k8s_cluster.children.kube_control_plane
              - all.children.target.children.k8s_cluster.children.kube_node
            action: delete_node
    - name: install-harbor
      title:
        zh: 安装Harbor
        en: Install Harbor
      steps:
        - name: 01-install-harbor
          title:
            zh: 安装 Harbor
            en: Install Harbor
  dependency:
    - name: kubernetes
      version: 1.28.15
      category: kubernetes
      artifact:
        type: "tarball"
        tarball_content_directory: kubernetes/server/bin/
        url:
          default: "https://dl.k8s.io/v${version}/kubernetes-server-${os}-${arch}.tar.gz"
        checksum:
          linux_arm64: sha256:https://dl.k8s.io/v${version}/SHA256SUMS
          linux_amd64: sha256:https://dl.k8s.io/v${version}/SHA256SUMS
    - name: containerd
      version: 1.7.27
      category: container_runtime
      artifact:
        type: "tarball"
        tarball_content_directory: bin/
        url:
          default: "https://github.com/containerd/containerd/releases/download/v${version}/containerd-${version}-${os}-${arch}.tar.gz"
        checksum:
          linux_arm64: sha256:https://github.com/containerd/containerd/releases/download/v${version}/containerd-${version}-${os}-${arch}.tar.gz.sha256sum
          linux_amd64: sha256:https://github.com/containerd/containerd/releases/download/v${version}/containerd-${version}-${os}-${arch}.tar.gz.sha256sum
    - name: runc
      version: 1.2.6
      category: container_runtime
      artifact:
        type: "binary"
        url:
          default: "https://github.com/opencontainers/runc/releases/download/v${version}/runc.${arch}"
        checksum:
          linux_arm64: sha256:https://github.com/opencontainers/runc/releases/download/v${version}/runc.sha256sum
          linux_amd64: sha256:https://github.com/opencontainers/runc/releases/download/v${version}/runc.sha256sum
    - name: nerdctl
      version: 1.7.7
      category: container_runtime
      artifact:
        type: "tarball"
        url:
          default: "https://github.com/containerd/nerdctl/releases/download/v${version}/nerdctl-${version}-${os}-${arch}.tar.gz"
        checksum:
          linux_arm64: sha256:https://github.com/containerd/nerdctl/releases/download/v${version}/SHA256SUMS
          linux_amd64: sha256:https://github.com/containerd/nerdctl/releases/download/v${version}/SHA256SUMS
    - name: docker
      version: 28.0.4
      category: container_runtime
      artifact:
        type: "tarball"
        tarball_content_directory: docker/
        url:
          linux_arm64: "https://download.docker.com/${os}/static/stable/aarch64/docker-${version}.tgz"
          linux_amd64: "https://download.docker.com/${os}/static/stable/x86_64/docker-${version}.tgz"
        checksum:
          linux_arm64: sha256:d3291093e8ed576ed9e237b24dc4556a9ed21ff25d4c26578df612cb6fe0480f
          linux_amd64: sha256:6b130fa5fb13516620d5ece0b63f63a495cede428bb2f9e24449022e9d72e0cb
    - name: docker-compose
      version: 2.35.1
      category: container_runtime
      artifact:
        type: "binary"
        url:
          linux_arm64: "https://github.com/docker/compose/releases/download/v${version}/docker-compose-${os}-aarch64"
          linux_amd64: "https://github.com/docker/compose/releases/download/v${version}/docker-compose-${os}-x86_64"
        checksum:
          linux_arm64: sha256:https://github.com/docker/compose/releases/download/v${version}/docker-compose-${os}-aarch64.sha256
          linux_amd64: sha256:https://github.com/docker/compose/releases/download/v${version}/docker-compose-${os}-x86_64.sha256
    - name: etcd
      version: 3.5.21
      category: etcd
      artifact:
        type: "tarball"
        tarball_content_directory: etcd-v${version}-${os}-${arch}/
        url:
          default: "https://github.com/etcd-io/etcd/releases/download/v${version}/etcd-v${version}-${os}-${arch}.tar.gz"
        checksum:
          linux_arm64: sha256:https://github.com/etcd-io/etcd/releases/download/v${version}/SHA256SUMS
          linux_amd64: sha256:https://github.com/etcd-io/etcd/releases/download/v${version}/SHA256SUMS
    - name: pause
      version: 3.8
      category: image
      artifact:
        type: "container_image"
        image:
          default: registry.k8s.io/pause:${version}
    - name: coredns
      version: 1.7.1
      category: image
      artifact:
        type: "container_image"
        image:
          default: coredns/coredns:${version}
    - name: keepalived
      version: 2.0.20
      category: image
      artifact:
        type: "container_image"
        image:
          default: osixia/keepalived:${version}
    - name: haproxy
      version: 2.2
      category: image
      artifact:
        type: "container_image"
        image:
          default: haproxy:${version}
    - name: calico-cni
      version: v3.23.2
      category: image
      artifact:
        type: "container_image"
        image:
          default: calico/cni:${version}
    - name: calico-node
      version: v3.23.2
      category: image
      artifact:
        type: "container_image"
        image:
          default: calico/node:${version}
    - name: calico-kube-controllers
      version: v3.23.2
      category: image
      artifact:
        type: "container_image"
        image:
          default: calico/kube-controllers:${version}
    - name: goharbor-chartmuseum-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/chartmuseum-photon:${version}
    - name: goharbor-harbor-core
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-core:${version}
    - name: goharbor-harbor-db
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-db:${version}
    - name: goharbor-harbor-exporter
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-exporter:${version}
    - name: goharbor-harbor-jobservice
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-jobservice:${version}
    - name: goharbor-harbor-log
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-log:${version}
    - name: goharbor-harbor-portal
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-portal:${version}
    - name: goharbor-harbor-registryctl
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-registryctl:${version}
    - name: goharbor-nginx-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/nginx-photon:${version}
    - name: goharbor-notary-server-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/notary-server-photon:${version}
    - name: goharbor-notary-signer-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/notary-signer-photon:${version}
    - name: goharbor-prepare
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/prepare:${version}
    - name: goharbor-redis-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/redis-photon:${version}
    - name: goharbor-registry-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/registry-photon:${version}
    - name: goharbor-trivy-adapter-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/trivy-adapter-photon:${version}
    - name: yq
      version: 4.48.2
      category: kubernetes
      artifact:
        type: "binary"
        url:
          default: "https://github.com/mikefarah/yq/releases/download/v${version}/yq_${os}_${arch}"
metadata:
  can_replace_to: null
  can_upgrade_from:
    exclude: null
    include:
      - spray-v2.21.0[a-c]_k8s-v1.26.[0-3]*_v4.[1-3]-amd64
      - spray-v2.20.0[a-b]_k8s-v1.25.[0-9]*_v3.[0-9]*-amd64
  issue_date: "2026-02-09"
  pangee_cluster_version:
    min: v2.0.0
  owner: shaohuanqing@chinamobile.com
  supported_feature:
    eviction_hard: true
  supported_os:
    - distribution: Ubuntu
      versions:
        - "20.04"
        - "22.04"
    - distribution: Anolis
      versions:
        - "8.4"
        - "8.5"
        - "8.6"
    - distribution: CentOS
      versions:
        - "7.6"
        - "7.8"
        - "7.9"
        - "8"
    - distribution: OracleLinux
      versions:
        - "8.5"
        - "8.7"
        - "9.1"
    - distribution: Rocky
      versions:
        - "8.5"
        - "8.7"
        - "9.1"
    - distribution: openEuler
      versions:
        - "20.03"
        - "22.03"
  type: pangee-cluster-resource-package
  version: v1.28.15_v1