start_command:
  - cat {{ root_dir }}/backup/deployments.txt | awk '{print "kubectl scale deployment --replicas="$3,"-n",$1,$2}' | sh
  - cat {{ root_dir }}/backup/statefulsets.txt | awk '{print "kubectl scale statefulset --replicas="$3,"-n",$1,$2}' | sh
