- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ copy_list }}"
  when: copy_list is defined

- name: Install
  shell: "{{ item }}"
  environment:
    PATH: "{{ root_dir }}/usr/bin:{{ ansible_env.PATH }}"
  loop: "{{ start_command }}"
  loop_control:
    label: "{{ item }}"
  when: start_command is defined
