- name: Check kubernetes Status
  hosts: kube_control_plane
  gather_facts: false
  strategy: free
  tasks:
    - name: |
        name: kube_status
        description:
          en: Check kube status
          zh: 检查 kube 状态
      shell: |+
        COUNT=$(kubectl get nodes | grep -c NotReady)
        if [ "$COUNT" == "0" ]; then
          echo "0"
        else
          kubectl get nodes | grep NotReady
        fi
      when: inventory_hostname == (groups['kube_control_plane'])[0]
