start_command:
  - |
    systemctl daemon-reload \
    && systemctl stop containerd \
    && systemctl disable containerd \
    && systemctl stop kubelet \
    && systemctl disable kubelet \
    && systemctl stop kube-proxy \
    && systemctl disable kube-proxy \
    {% if inventory_hostname in groups['kube_control_plane'] %}
    && systemctl stop kube-apiserver \
    && systemctl disable kube-apiserver \
    && systemctl stop kube-controller-manager \
    && systemctl disable kube-controller-manager \
    && systemctl stop kube-scheduler \
    && systemctl disable kube-scheduler \
    {% endif %}
    || true
